### ISSUE TITLE
Calliope mini stürzt beim Benutzen der Erweiterung ab

### ISSUE THREAD

**Issue by AmandoP** [MKleinSB/pxt-OLED-SSD1306#1]
Während die "Games"-Erweiterung (pxt-OLED-SSD1306-GAMES) funktioniert, stürzt der Calliope mini (v1.3 und v2.1 getestet) bei der Benutzung jeglicher Blöcke dieses Pakets ab. Das Abstürzen äußert sich durch eine flackernde LED-Matrix am Calliope mini. Das OLED-Display bleibt schwarz.

**Comment by MKleinSB** [comment]
Ja, durch das Neukompilieren hat der Speicher nicht mehr gereicht. Musste jetzt Bluetooth deaktivieren. Läuft wieder ;-)
